spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/how2j/springcloudConfig/
          searchPaths: respo
          #          uri: https://github.com/caoxx123/springcloud/
#          search-paths:#          - springcloudconfig
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/